name: eraser_example
description: Demonstrates how to use the eraser plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  eraser:
    path: ../
  move_to_background: ^1.0.2
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  http: ^0.13.3
  googleapis_auth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - privatekey/